# Sentiment Analysis with an RNN

In this notebook, you'll implement a recurrent neural network that performs sentiment analysis. 
>Using an RNN rather than a strictly feedforward network is more accurate since we can include information about the *sequence* of words. 

Here we'll use a dataset of movie reviews, accompanied by sentiment labels: positive or negative.

<img src="assets/reviews_ex.png" width=40%>

### Network Architecture

The architecture for this network is shown below.

<img src="assets/network_diagram.png" width=40%>

>**First, we'll pass in words to an embedding layer.** We need an embedding layer because we have tens of thousands of words, so we'll need a more efficient representation for our input data than one-hot encoded vectors. You should have seen this before from the Word2Vec lesson. You can actually train an embedding with the Skip-gram Word2Vec model and use those embeddings as input, here. However, it's good enough to just have an embedding layer and let the network learn a different embedding table on its own. *In this case, the embedding layer is for dimensionality reduction, rather than for learning semantic representations.*

>**After input words are passed to an embedding layer, the new embeddings will be passed to LSTM cells.** The LSTM cells will add *recurrent* connections to the network and give us the ability to include information about the *sequence* of words in the movie review data. 

>**Finally, the LSTM outputs will go to a sigmoid output layer.** We're using a sigmoid function because positive and negative = 1 and 0, respectively, and a sigmoid will output predicted, sentiment values between 0-1. 

We don't care about the sigmoid outputs except for the **very last one**; we can ignore the rest. We'll calculate the loss by comparing the output at the last time step and the training label (pos or neg).

---
### Load in and visualize the data

In [1]:
import numpy as np

# read data from text files
with open('data/reviews.txt', 'r') as f:
    reviews = f.read()
with open('data/labels.txt', 'r') as f:
    labels = f.read()

In [2]:
print(reviews[:2000])
print()
print(labels[:20])

bromwell high is a cartoon comedy . it ran at the same time as some other programs about school life  such as  teachers  . my   years in the teaching profession lead me to believe that bromwell high  s satire is much closer to reality than is  teachers  . the scramble to survive financially  the insightful students who can see right through their pathetic teachers  pomp  the pettiness of the whole situation  all remind me of the schools i knew and their students . when i saw the episode in which a student repeatedly tried to burn down the school  i immediately recalled . . . . . . . . . at . . . . . . . . . . high . a classic line inspector i  m here to sack one of your teachers . student welcome to bromwell high . i expect that many adults of my age think that bromwell high is far fetched . what a pity that it isn  t   
story of a man who has unnatural feelings for a pig . starts out with a opening scene that is a terrific example of absurd comedy . a formal orchestra audience is turn

## Data pre-processing

The first step when building a neural network model is getting your data into the proper form to feed into the network. Since we're using embedding layers, we'll need to encode each word with an integer. We'll also want to clean it up a bit.

You can see an example of the reviews data above. Here are the processing steps, we'll want to take:
>* We'll want to get rid of periods and extraneous punctuation.
* Also, you might notice that the reviews are delimited with newline characters `\n`. To deal with those, I'm going to split the text into each review using `\n` as the delimiter. 
* Then I can combined all the reviews back together into one big string.

First, let's remove all punctuation. Then get all the text without the newlines and split it into individual words.

In [3]:
from string import punctuation

print(punctuation)

# get rid of punctuation
reviews = reviews.lower() # lowercase, standardize
all_text = ''.join([c for c in reviews if c not in punctuation])

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [4]:
# split by new lines and spaces
reviews_split = all_text.split('\n')
all_text = ' '.join(reviews_split)
print(reviews_split[0].split())
# create a list of words
words = all_text.split()


['bromwell', 'high', 'is', 'a', 'cartoon', 'comedy', 'it', 'ran', 'at', 'the', 'same', 'time', 'as', 'some', 'other', 'programs', 'about', 'school', 'life', 'such', 'as', 'teachers', 'my', 'years', 'in', 'the', 'teaching', 'profession', 'lead', 'me', 'to', 'believe', 'that', 'bromwell', 'high', 's', 'satire', 'is', 'much', 'closer', 'to', 'reality', 'than', 'is', 'teachers', 'the', 'scramble', 'to', 'survive', 'financially', 'the', 'insightful', 'students', 'who', 'can', 'see', 'right', 'through', 'their', 'pathetic', 'teachers', 'pomp', 'the', 'pettiness', 'of', 'the', 'whole', 'situation', 'all', 'remind', 'me', 'of', 'the', 'schools', 'i', 'knew', 'and', 'their', 'students', 'when', 'i', 'saw', 'the', 'episode', 'in', 'which', 'a', 'student', 'repeatedly', 'tried', 'to', 'burn', 'down', 'the', 'school', 'i', 'immediately', 'recalled', 'at', 'high', 'a', 'classic', 'line', 'inspector', 'i', 'm', 'here', 'to', 'sack', 'one', 'of', 'your', 'teachers', 'student', 'welcome', 'to', 'bromw

In [5]:
words[:30]

['bromwell',
 'high',
 'is',
 'a',
 'cartoon',
 'comedy',
 'it',
 'ran',
 'at',
 'the',
 'same',
 'time',
 'as',
 'some',
 'other',
 'programs',
 'about',
 'school',
 'life',
 'such',
 'as',
 'teachers',
 'my',
 'years',
 'in',
 'the',
 'teaching',
 'profession',
 'lead',
 'me']

### Encoding the words

The embedding lookup requires that we pass in integers to our network. The easiest way to do this is to create dictionaries that map the words in the vocabulary to integers. Then we can convert each of our reviews into integers so they can be passed into the network.

> **Exercise:** Now you're going to encode the words with integers. Build a dictionary that maps words to integers. Later we're going to pad our input vectors with zeros, so make sure the integers **start at 1, not 0**.
> Also, convert the reviews to integers and store the reviews in a new list called `reviews_ints`. 

In [6]:
# feel free to use this import 
from collections import Counter

## Build a dictionary that maps words to integers
word_counter = Counter(words)

#encode words
words_sorted = sorted(set(words),key = word_counter.get,reverse=True)
#create dict that maps each word to an integer starting at one.
vocab_to_int = {}
for val,key in enumerate(words_sorted,1):
    vocab_to_int[key] = val
#create dict that maps each integer to a word starting at one.
int_to_vocab = {}
for key,val in enumerate(words_sorted,1):
    int_to_vocab[key] = val




In [7]:
## use the dict to tokenize each review in reviews_split
## store the tokenized reviews in reviews_ints
reviews_ints = []
for review in reviews_split:
    encoded_labels = []
    for word in review.split():
        encoded_labels.append(vocab_to_int[word])
    reviews_ints.append(encoded_labels)
    

**Test your code**

As a text that you've implemented the dictionary correctly, print out the number of unique words in your vocabulary and the contents of the first, tokenized review.

In [8]:
# stats about vocabulary
print('Unique words: ', len(((vocab_to_int))))  
# should ~ 74000+
#print()

# print tokens in first review
print('Tokenized review: \n', (reviews_ints[:1]))

Unique words:  74072
Tokenized review: 
 [[22153, 308, 6, 3, 1051, 207, 8, 2141, 32, 1, 171, 57, 15, 49, 81, 5818, 44, 382, 110, 140, 15, 5225, 60, 154, 9, 1, 4977, 5863, 475, 71, 5, 260, 12, 22153, 308, 13, 1980, 6, 74, 2403, 5, 614, 73, 6, 5225, 1, 24962, 5, 1988, 10378, 1, 5786, 1502, 36, 51, 66, 204, 145, 67, 1203, 5225, 20095, 1, 39073, 4, 1, 221, 883, 31, 3002, 71, 4, 1, 5809, 10, 687, 2, 67, 1502, 54, 10, 216, 1, 384, 9, 62, 3, 1408, 3695, 783, 5, 3493, 180, 1, 382, 10, 1214, 13753, 32, 308, 3, 349, 341, 2928, 10, 143, 127, 5, 7777, 30, 4, 129, 5225, 1408, 2330, 5, 22153, 308, 10, 528, 12, 109, 1450, 4, 60, 543, 102, 12, 22153, 308, 6, 227, 4160, 48, 3, 2212, 12, 8, 215, 23]]


### Encoding the labels

Our labels are "positive" or "negative". To use these labels in our network, we need to convert them to 0 and 1.

> **Exercise:** Convert labels from `positive` and `negative` to 1 and 0, respectively, and place those in a new list, `encoded_labels`.

In [9]:
# 1=positive, 0=negative label conversion
labels_list = labels.split('\n')

encoded_labels = []
for label in labels_list:
    if label == 'positive':
        encoded_labels.append(1)
    else:
        encoded_labels.append(0)



### Removing Outliers

As an additional pre-processing step, we want to make sure that our reviews are in good shape for standard processing. That is, our network will expect a standard input text size, and so, we'll want to shape our reviews into a specific length. We'll approach this task in two main steps:

1. Getting rid of extremely long or short reviews; the outliers
2. Padding/truncating the remaining data so that we have reviews of the same length.

<img src="assets/outliers_padding_ex.png" width=40%>

Before we pad our review text, we should check for reviews of extremely short or long lengths; outliers that may mess with our training.

In [10]:
# outlier review stats
review_lens = Counter([len(x) for x in reviews_ints])
print("Zero-length reviews: {}".format(review_lens[0]))
print("Maximum review length: {}".format(max(review_lens)))
print(len(reviews_ints) ,len(encoded_labels))

Zero-length reviews: 1
Maximum review length: 2514
25001 25001


Okay, a couple issues here. We seem to have one review with zero length. And, the maximum review length is way too many steps for our RNN. We'll have to remove any super short reviews and truncate super long reviews. This removes outliers and should allow our model to train more efficiently.

> **Exercise:** First, remove *any* reviews with zero length from the `reviews_ints` list and their corresponding label in `encoded_labels`.

In [11]:
print('Number of reviews before removing outliers: ', len(reviews_ints))

## remove any reviews/labels with zero length from the reviews_ints list.
for review in range(len(reviews_ints)):
    if len(reviews_ints[review]) == 0:
        del reviews_ints[review]
        del encoded_labels[review]


print('Number of reviews after removing outliers: ', len(reviews_ints))

Number of reviews before removing outliers:  25001
Number of reviews after removing outliers:  25000


---
## Padding sequences

To deal with both short and very long reviews, we'll pad or truncate all our reviews to a specific length. For reviews shorter than some `seq_length`, we'll pad with 0s. For reviews longer than `seq_length`, we can truncate them to the first `seq_length` words. A good `seq_length`, in this case, is 200.

> **Exercise:** Define a function that returns an array `features` that contains the padded data, of a standard size, that we'll pass to the network. 
* The data should come from `review_ints`, since we want to feed integers to the network. 
* Each row should be `seq_length` elements long. 
* For reviews shorter than `seq_length` words, **left pad** with 0s. That is, if the review is `['best', 'movie', 'ever']`, `[117, 18, 128]` as integers, the row will look like `[0, 0, 0, ..., 0, 117, 18, 128]`. 
* For reviews longer than `seq_length`, use only the first `seq_length` words as the feature vector.

As a small example, if the `seq_length=10` and an input review is: 
```
[117, 18, 128]
```
The resultant, padded sequence should be: 

```
[0, 0, 0, 0, 0, 0, 0, 117, 18, 128]
```

**Your final `features` array should be a 2D array, with as many rows as there are reviews, and as many columns as the specified `seq_length`.**

This isn't trivial and there are a bunch of ways to do this. But, if you're going to be building your own deep learning networks, you're going to have to get used to preparing your data.

In [12]:
def pad_features(reviews_ints, seq_length,predict = False):
    ''' Return features of review_ints, where each review is padded with 0's 
        or truncated to the input seq_length.
    '''
    ## implement function
    #create empty numpy array of correct shape
    features = np.zeros((len(reviews_ints),seq_length),dtype =int )
    #start a count at 0 to correctly put review in correct row
    count = 0
    if predict == True:
        for word in reviews_ints:
            if len(reviews_ints) < seq_length:
                while len(reviews_ints) < seq_length:
                    reviews_ints.insert(0,0)
            
         #if len review is too long , clip it and add it to the array
            elif len(reviews_ints) > seq_length:
                reviews_ints = review_ints[:seq_length]
                
            else:
                #if its the right size, add it straight up.
                reviews_ints = reviews_ints
        return reviews_ints

    for review in reviews_ints:
        #if len review is too short , add 0's to the left until its the proper sequence length and add it to the arrau.
        if len(review) < seq_length:
            while len(review) < seq_length:
                review.insert(0,0)
            features[count] = review
         #if len review is too long , clip it and add it to the array
        elif len(review) > seq_length:
            review = review[:seq_length]
            features[count] = review
        else:
            #if its the right size, add it straight up.
            features[count] = review
        count += 1

            
    
    return features

In [13]:
# Test your implementation!

seq_length = 200

features = pad_features(reviews_ints, seq_length=seq_length)

## test statements - do not change - ##
assert len(features)==len(reviews_ints), "Your features should have as many rows as reviews."
assert len(features[0])==seq_length, "Each feature row should contain seq_length values."

# print first 10 values of the first 30 batches 
print(features[:30,:200])

[[    0     0     0 ...     8   215    23]
 [    0     0     0 ...    29   108  3340]
 [23827    42 66198 ...   483    17     3]
 ...
 [    0     0     0 ...    59   429  1779]
 [    0     0     0 ...    55   201    18]
 [    0     0     0 ...    18    17  1192]]


## Training, Validation, Test

With our data in nice shape, we'll split it into training, validation, and test sets.

> **Exercise:** Create the training, validation, and test sets. 
* You'll need to create sets for the features and the labels, `train_x` and `train_y`, for example. 
* Define a split fraction, `split_frac` as the fraction of data to **keep** in the training set. Usually this is set to 0.8 or 0.9. 
* Whatever data is left will be split in half to create the validation and *testing* data.

In [14]:
split_frac = 0.8
from sklearn.model_selection import train_test_split

## split data into training, validation, and test data (features and labels, x and y)
X_train, X_test, y__train, y_test = train_test_split(features, np.array(encoded_labels), train_size = split_frac, test_size = 0.2)
X_valid, X_test, Y_valid, Y_test = train_test_split(X_test, y_test, train_size = 0.5, test_size = 0.5)


## print out the shapes of your resultant feature data

print(X_train.shape)
print(X_valid.shape)
print(X_test.shape)

(20000, 200)
(2500, 200)
(2500, 200)


**Check your work**

With train, validation, and test fractions equal to 0.8, 0.1, 0.1, respectively, the final, feature data shapes should look like:
```
                    Feature Shapes:
Train set: 		 (20000, 200) 
Validation set: 	(2500, 200) 
Test set: 		  (2500, 200)
```

---
## DataLoaders and Batching

After creating training, test, and validation data, we can create DataLoaders for this data by following two steps:
1. Create a known format for accessing our data, using [TensorDataset](https://pytorch.org/docs/stable/data.html#) which takes in an input set of data and a target set of data with the same first dimension, and creates a dataset.
2. Create DataLoaders and batch our training, validation, and test Tensor datasets.

```
train_data = TensorDataset(torch.from_numpy(train_x), torch.from_numpy(train_y))
train_loader = DataLoader(train_data, batch_size=batch_size)
```

This is an alternative to creating a generator function for batching our data into full batches.

In [15]:
import torch
from torch.utils.data import TensorDataset, DataLoader

# create Tensor datasets
train_data = TensorDataset(torch.from_numpy(X_train), torch.from_numpy(y__train))
valid_data = TensorDataset(torch.from_numpy(X_valid), torch.from_numpy(Y_valid))
test_data = TensorDataset(torch.from_numpy(X_test), torch.from_numpy(Y_test))

# dataloaders
batch_size = 50

# make sure to SHUFFLE your data
train_loader = DataLoader(train_data, shuffle=True, batch_size=batch_size)
valid_loader = DataLoader(valid_data, shuffle=True, batch_size=batch_size)
test_loader = DataLoader(test_data, shuffle=True, batch_size=batch_size)

In [16]:
# obtain one batch of training data
dataiter = iter(train_loader)
sample_x, sample_y = dataiter.next()

print('Sample input size: ', sample_x.size()) # batch_size, seq_length
print('Sample input: \n', sample_x)
print()
print('Sample label size: ', sample_y.size()) # batch_size
print('Sample label: \n', sample_y)

Sample input size:  torch.Size([50, 200])
Sample input: 
 tensor([[   0,    0,    0,  ...,  355,    5,  122],
        [ 157, 2700, 4258,  ...,  155,  339,    6],
        [ 673, 1643,  512,  ...,   16, 2476,    8],
        ...,
        [   0,    0,    0,  ...,  139,  108,    8],
        [   0,    0,    0,  ..., 1431,   11,   63],
        [2954,   56,    2,  ...,  304, 3495,    1]], dtype=torch.int32)

Sample label size:  torch.Size([50])
Sample label: 
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
        1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
        1, 0], dtype=torch.int32)


---
# Sentiment Network with PyTorch

Below is where you'll define the network.

<img src="assets/network_diagram.png" width=40%>

The layers are as follows:
1. An [embedding layer](https://pytorch.org/docs/stable/nn.html#embedding) that converts our word tokens (integers) into embeddings of a specific size.
2. An [LSTM layer](https://pytorch.org/docs/stable/nn.html#lstm) defined by a hidden_state size and number of layers
3. A fully-connected output layer that maps the LSTM layer outputs to a desired output_size
4. A sigmoid activation layer which turns all outputs into a value 0-1; return **only the last sigmoid output** as the output of this network.

### The Embedding Layer

We need to add an [embedding layer](https://pytorch.org/docs/stable/nn.html#embedding) because there are 74000+ words in our vocabulary. It is massively inefficient to one-hot encode that many classes. So, instead of one-hot encoding, we can have an embedding layer and use that layer as a lookup table. You could train an embedding layer using Word2Vec, then load it here. But, it's fine to just make a new layer, using it for only dimensionality reduction, and let the network learn the weights.


### The LSTM Layer(s)

We'll create an [LSTM](https://pytorch.org/docs/stable/nn.html#lstm) to use in our recurrent network, which takes in an input_size, a hidden_dim, a number of layers, a dropout probability (for dropout between multiple layers), and a batch_first parameter.

Most of the time, you're network will have better performance with more layers; between 2-3. Adding more layers allows the network to learn really complex relationships. 

> **Exercise:** Complete the `__init__`, `forward`, and `init_hidden` functions for the SentimentRNN model class.

Note: `init_hidden` should initialize the hidden and cell state of an lstm layer to all zeros, and move those state to GPU, if available.

In [25]:
# First checking if GPU is available
train_on_gpu=torch.cuda.is_available()

if(train_on_gpu):
    print('Training on GPU.')
else:
    print('No GPU available, training on CPU.')

Training on GPU.


In [26]:
import torch.nn as nn
import torch.nn.functional as F
class SentimentRNN(nn.Module):
    """
    The RNN model that will be used to perform Sentiment analysis.
    """

    def __init__(self, vocab_size, output_size, embedding_dim, hidden_dim, n_layers, drop_prob=0.5):
        """
        Initialize the model by setting up the layers.
        """
        super(SentimentRNN, self).__init__()

        self.output_size = output_size
        self.n_layers = n_layers
        self.hidden_dim = hidden_dim
        
        # define all layers
        #define embedding layer
        self.embd = nn.Embedding(vocab_size,embedding_dim)
        #define lstm cells
        self.lstm = nn.LSTM(embedding_dim,hidden_dim,n_layers,batch_first=True,dropout=drop_prob)
        #define linear layer
        self.fc = nn.Linear(hidden_dim,output_size)
        #define dropout layer
        self.dropout = nn.Dropout(p = drop_prob)
        
        
    def forward(self, x, hidden):
        """
        Perform a forward pass of our model on some input and hidden state.
        """
        #reserve batch_size
        batch_size = x.shape[0]
        #pass vocab thru embedding layer to reduce dimensionality
        x = x.long()
        x = self.embd(x)
        #pass thru lstm cells
        x,hidden = self.lstm(x,hidden)
        #dropout to reduce overfitting
        x = self.dropout(x)
        #flatten the output to fit into linear layer
        x = x.contiguous().view(-1,self.hidden_dim)
        #send input into linear layer
        x = self.fc(x)
        #apply sigmoid function
        sig_out = F.sigmoid(x)
        #reshape to have batch_size first
        sig_out = sig_out.view(batch_size,-1)
        # get last batch of labels , we are only interested in the final output as we are using an RNN, as the final output (last batch) will be affected by all the previous memory,          earlier outputs are not important as they are npt affected by al the previous memory.
        sig_out = sig_out[:, -1]        
        # return last sigmoid output and hidden state
        return sig_out, hidden
    
    
    def init_hidden(self, batch_size):
        ''' Initializes hidden state '''
        # Create two new tensors with sizes n_layers x batch_size x hidden_dim,
        # initialized to zero, for hidden state and cell state of LSTM
        weight = next(self.parameters()).data
        #initialize weights at 0 (long term and short term memory of LSTM)
        hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda(),
                  weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda())
        return hidden
        

## Instantiate the network

Here, we'll instantiate the network. First up, defining the hyperparameters.

* `vocab_size`: Size of our vocabulary or the range of values for our input, word tokens.
* `output_size`: Size of our desired output; the number of class scores we want to output (pos/neg).
* `embedding_dim`: Number of columns in the embedding lookup table; size of our embeddings.
* `hidden_dim`: Number of units in the hidden layers of our LSTM cells. Usually larger is better performance wise. Common values are 128, 256, 512, etc.
* `n_layers`: Number of LSTM layers in the network. Typically between 1-3

> **Exercise:** Define the model  hyperparameters.


In [27]:

# Instantiate the model w/ hyperparams
vocab_size = len(vocab_to_int)+1 # +1 for the 0 padding + our word tokens
output_size = 1
embedding_dim = 400
hidden_dim = 256
n_layers = 3

net = SentimentRNN(vocab_size, output_size, embedding_dim, hidden_dim, n_layers)

print(net)

SentimentRNN(
  (embd): Embedding(74073, 400)
  (lstm): LSTM(400, 256, num_layers=3, batch_first=True, dropout=0.5)
  (fc): Linear(in_features=256, out_features=1, bias=True)
  (dropout): Dropout(p=0.5, inplace=False)
)


---
## Training

Below is the typical training code. If you want to do this yourself, feel free to delete all this code and implement it yourself. You can also add code to save a model by name.

>We'll also be using a new kind of cross entropy loss, which is designed to work with a single Sigmoid output. [BCELoss](https://pytorch.org/docs/stable/nn.html#bceloss), or **Binary Cross Entropy Loss**, applies cross entropy loss to a single value between 0 and 1.

We also have some data and training hyparameters:

* `lr`: Learning rate for our optimizer.
* `epochs`: Number of times to iterate through the training dataset.
* `clip`: The maximum gradient value to clip at (to prevent exploding gradients).

In [28]:
# loss and optimization functions
lr=0.001

criterion = nn.BCELoss()
optimizer = torch.optim.Adam(net.parameters(), lr=lr)


In [29]:
# training params

epochs = 4 # 3-4 is approx where I noticed the validation loss stop decreasing

counter = 0
print_every = 100
clip=5 # gradient clipping

# move model to GPU, if available
if(train_on_gpu):
    net.cuda()

net.train()
# train for some number of epochs
for e in range(epochs):
    # initialize hidden state
    h = net.init_hidden(batch_size)

    # batch loop
    for inputs, labels in train_loader:
        counter += 1

        if(train_on_gpu):
            inputs, labels = inputs.cuda(), labels.cuda()

        # Creating new variables for the hidden state, otherwise
        # we'd backprop through the entire training history
        h = tuple([each.data for each in h])

        # zero accumulated gradients
        net.zero_grad()

        # get the output from the model
        output, h = net(inputs, h)
        
        # calculate the loss and perform backprop
        loss = criterion(output.squeeze(), labels.float())
        loss.backward()
        # `clip_grad_norm` helps prevent the exploding gradient problem in RNNs / LSTMs.
        nn.utils.clip_grad_norm_(net.parameters(), clip)
        optimizer.step()

        # loss stats
        if counter % print_every == 0:
            # Get validation loss
            val_h = net.init_hidden(batch_size)
            val_losses = []
            net.eval()
            for inputs, labels in valid_loader:

                # Creating new variables for the hidden state, otherwise
                # we'd backprop through the entire training history
                val_h = tuple([each.data for each in val_h])

                if(train_on_gpu):
                    inputs, labels = inputs.cuda(), labels.cuda()

                output, val_h = net(inputs, val_h)
                val_loss = criterion(output.squeeze(), labels.float())

                val_losses.append(val_loss.item())
                
            net.train()
            print("Epoch: {}/{}...".format(e+1, epochs),
                  "Step: {}...".format(counter),
                  "Loss: {:.6f}...".format(loss.item()),
                  "Val Loss: {:.6f}".format(np.mean(val_losses)))

Epoch: 1/4... Step: 100... Loss: 0.592703... Val Loss: 0.637141
Epoch: 1/4... Step: 200... Loss: 0.703645... Val Loss: 0.692934
Epoch: 1/4... Step: 300... Loss: 0.693043... Val Loss: 0.692159
Epoch: 1/4... Step: 400... Loss: 0.681617... Val Loss: 0.689068
Epoch: 2/4... Step: 500... Loss: 0.714300... Val Loss: 0.664513
Epoch: 2/4... Step: 600... Loss: 0.691784... Val Loss: 0.690938
Epoch: 2/4... Step: 700... Loss: 0.746050... Val Loss: 0.695141
Epoch: 2/4... Step: 800... Loss: 0.655866... Val Loss: 0.622707
Epoch: 3/4... Step: 900... Loss: 0.523704... Val Loss: 0.525310
Epoch: 3/4... Step: 1000... Loss: 0.742267... Val Loss: 0.638053
Epoch: 3/4... Step: 1100... Loss: 0.333520... Val Loss: 0.439916
Epoch: 3/4... Step: 1200... Loss: 0.410217... Val Loss: 0.412470
Epoch: 4/4... Step: 1300... Loss: 0.242683... Val Loss: 0.426985
Epoch: 4/4... Step: 1400... Loss: 0.349314... Val Loss: 0.412287
Epoch: 4/4... Step: 1500... Loss: 0.213838... Val Loss: 0.400556
Epoch: 4/4... Step: 1600... Loss: 

---
## Testing

There are a few ways to test your network.

* **Test data performance:** First, we'll see how our trained model performs on all of our defined test_data, above. We'll calculate the average loss and accuracy over the test data.

* **Inference on user-generated data:** Second, we'll see if we can input just one example review at a time (without a label), and see what the trained model predicts. Looking at new, user input data like this, and predicting an output label, is called **inference**.

In [41]:
# Get test data loss and accuracy

test_losses = [] # track loss
num_correct = 0

# init hidden state
h = net.init_hidden(batch_size)

net.eval()
# iterate over test data
for inputs, labels in test_loader:

    # Creating new variables for the hidden state, otherwise
    # we'd backprop through the entire training history
    h = tuple([each.data for each in h])

    if(train_on_gpu):
        inputs, labels = inputs.cuda(), labels.cuda()
    
    # get predicted outputs
    output, h = net(inputs, h)
    
    # calculate loss
    test_loss = criterion(output.squeeze(), labels.float())
    test_losses.append(test_loss.item())
    
    # convert output probabilities to predicted class (0 or 1)
    pred = torch.round(output.squeeze())  # rounds to the nearest integer
    
    # compare predictions to true label
    correct_tensor = pred.eq(labels.float().view_as(pred))
    correct = np.squeeze(correct_tensor.numpy()) if not train_on_gpu else np.squeeze(correct_tensor.cpu().numpy())
    num_correct += np.sum(correct)


# -- stats! -- ##
# avg test loss
print("Test loss: {:.3f}".format(np.mean(test_losses)))

# accuracy over all test data
test_acc = num_correct/len(test_loader.dataset)
print("Test accuracy: {:.3f}".format(test_acc))

)
tensor([0.9728, 0.0165, 0.0166, 0.9799, 0.0255, 0.0213, 0.0189, 0.9667, 0.0164,
        0.7211, 0.0298, 0.9676, 0.0167, 0.0164, 0.2887, 0.0205, 0.0227, 0.0176,
        0.0162, 0.0183, 0.0232, 0.1191, 0.3439, 0.9103, 0.8706, 0.9816, 0.0165,
        0.0171, 0.3776, 0.0176, 0.9761, 0.0172, 0.9777, 0.9823, 0.9812, 0.1244,
        0.9834, 0.9753, 0.0208, 0.9750, 0.0204, 0.0458, 0.0186, 0.9562, 0.6332,
        0.0185, 0.0167, 0.9826, 0.0265, 0.0172], device='cuda:0',
       grad_fn=<SelectBackward>)
tensor([0.1220, 0.0167, 0.9596, 0.9682, 0.8330, 0.0819, 0.0235, 0.0247, 0.9786,
        0.0363, 0.9793, 0.0182, 0.8661, 0.0291, 0.9048, 0.8476, 0.9753, 0.0874,
        0.0196, 0.7431, 0.0180, 0.9806, 0.0276, 0.9829, 0.0213, 0.9760, 0.9797,
        0.0163, 0.2056, 0.5332, 0.9795, 0.0336, 0.0390, 0.9832, 0.9806, 0.1353,
        0.9833, 0.0204, 0.9823, 0.1759, 0.9760, 0.0376, 0.0226, 0.9313, 0.0266,
        0.9798, 0.0178, 0.9820, 0.0178, 0.0165], device='cuda:0',
       grad_fn=<SelectBackward>)


### Inference on a test review

You can change this test_review to any text that you want. Read it and think: is it pos or neg? Then see if your model predicts correctly!
    
> **Exercise:** Write a `predict` function that takes in a trained net, a plain text_review, and a sequence length, and prints out a custom statement for a positive or negative review!
* You can use any functions that you've already defined or define any helper functions you want to complete `predict`, but it should just take in a trained net, a text review, and a sequence length.


In [31]:
# negative test review
test_review_neg = 'The worst movie I have seen; acting was terrible and I want my money back. This movie had bad acting and the dialogue was slow.'


In [32]:
def tokenize(test_review):
    reviews = test_review.lower() # lowercase, standardize
    #remove punctuation
    punc_removed_review = ''.join([c for c in reviews if c not in punctuation])
    tokenized_review = []
    #tokenize the vocab in the review
    for word in punc_removed_review.split():
        tokenized_review.append(vocab_to_int[word])
    return tokenized_review
    
    

In [33]:
print(tokenize(test_review_neg))

[1, 247, 18, 10, 28, 108, 113, 14, 388, 2, 10, 181, 60, 273, 144, 11, 18, 68, 76, 113, 2, 1, 410, 14, 539]


In [87]:
def predict(net, test_review, sequence_length=200):
    ''' Prints out whether a give review is predicted to be 
        positive or negative in sentiment, using a trained model.
        
        params:
        net - A trained net 
        test_review - a review made of normal text and punctuation
        sequence_length - the padded length of a review
        '''
    net.eval()
    test_review = tokenize(test_review)
    padded_review = pad_features(test_review,sequence_length,predict = True)
    padded_review = torch.Tensor(padded_review).cuda()
    
    padded_review = padded_review.unsqueeze(0)
   
    h = net.init_hidden(1)
    
    pred,h = net(padded_review,h)
    pred_round = torch.round(pred.squeeze()).item()
    
    if pred_round == 1.0:
        print('This review is positive.')
    else:
        print('This review is negative.')
    # print custom response based on whether test_review is pos/neg
    
        

In [88]:
# positive test review
test_review_pos = 'This movie had the best acting and the dialogue was so good. I loved it.'
print(tokenize(test_review_pos))

[11, 18, 68, 1, 117, 113, 2, 1, 410, 14, 37, 50, 10, 445, 8]


In [89]:
# call function
# try negative and positive reviews!
seq_length=200

predict(net, test_review_neg, seq_length)

This review is negative.


### Try out test_reviews of your own!

Now that you have a trained model and a predict function, you can pass in _any_ kind of text and this model will predict whether the text has a positive or negative sentiment. Push this model to its limits and try to find what words it associates with positive or negative.

Later, you'll learn how to deploy a model like this to a production environment so that it can respond to any kind of user data put into a web app!

tensor([0.2727], device='cuda:0', grad_fn=<SelectBackward>)
This review is negative.
